use_frameworks!

platform :ios, '8.0'

target 'wp_common_sdks_Example' do
  pod 'wp_common_sdks', :path => '../'

  target 'wp_common_sdks_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
